name: Global CI/CD
on:
  pull_request:
    types: [open]
jobs:
  merge-to-dev:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      github.event.pullpull_request.base.ref == 'development' &&
      startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
    - name: Running the test of merging between dev and feature
      run: |
        echo "Start testing"
        sleep 5
        echo "Done testing"
        
